# Generated by Django 3.1 on 2021-11-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('votes', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
                ('isRated', models.BooleanField()),
                ('daysLeftToRegister', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=100)),
                ('commentBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.user')),
                ('parentComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.comment')),
                ('parentContest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
            ],
        ),
    ]
