# Generated by Django 3.1 on 2021-11-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20211114_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.user2'),
        ),
    ]
