# Generated by Django 3.1 on 2021-11-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20211114_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='password',
            field=models.CharField(default='asd', max_length=30),
        ),
    ]
