# Generated by Django 3.1 on 2021-11-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_user2_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
