# Generated by Django 3.1 on 2021-11-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20211114_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
