export const GET_LEADS = "GET_LEADS";
export const DELETE_LEADS = "DELETE_LEADS";
export const POST_LEADS = "POST_LEADS";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const POST_USER = "POST_USER";
export const GET_CONTESTS = "GET_LEADS";
export const UPDATE_DETAILS_CONTEST = "UPDATE_DETAILS_CONTEST";
export const GET_DETAILS_CONTEST = "GET_DETAILS_CONTEST";
export const POST_COMMENT = "POST_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";



